<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMrTWz33b86nfIrgaW9jE_t-7VCcqJtjL-pg&amp;s" class="sFlh5c FyHeAf" alt="GitHub - numpy/numpy: The fundamental package for scientific computing with  Python." jsname="JuXqh" style="max-width: 800px; height: 157px; margin: 0px; width: 349px;" data-ilt="1738124867915">

<img src="https://decodingdatascience.com/wp-content/uploads/2023/10/numpy1.png" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 743px; height: 244px; margin: 0px; width: 351px;" alt="Numpy: The Foundation of Data Science and AI - Decoding Data Science" jsname="kn3ccd" aria-hidden="false">

- NumPy is a Python library for numerical computing that provides efficient array operations, mathematical functions, and matrix manipulations, making it essential for data science and scientific computing.

- **NumPy: Numerical Python**

- NumPy is a powerful module for performing mathematical operations efficiently.

- While the **math** module provides basic mathematical functions, **NumPy** offers enhanced capabilities.

- With NumPy, complex mathematical computations can be performed with ease.

- It allows representing numbers in various forms:

   - **Lists:** Basic level representation of elements.
   - **Arrays:** A fundamental structure in the NumPy package.
   - **Tensors:** Used in deep learning frameworks like TensorFlow.
   - **Torch:** Utilized in the PyTorch library for advanced computations.


In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
l1=[1,2,3,4]
arr1=np.array(l1)
arr1

array([1, 2, 3, 4])

In [7]:
type(l1)

list

In [9]:
type(arr1) # ndarray == n dimensional array

numpy.ndarray

In [11]:
l1=[1,2,3,4]
l2=[20,30,40,50]
[i*j for i,j in zip(l1,l2)]

[20, 60, 120, 200]

In [13]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
arr1*arr2

array([ 10,  40,  90, 160])

In [15]:
arr2-arr1

array([ 9, 18, 27, 36])

In [17]:
arr2+arr1

array([11, 22, 33, 44])

In [19]:
arr1/arr2

array([0.1, 0.1, 0.1, 0.1])

In [21]:
arr1-arr2

array([ -9, -18, -27, -36])

In [23]:
op=arr1*arr2
list(op)

[10, 40, 90, 160]

In [25]:
op.tolist()

[10, 40, 90, 160]

**NumPy always performs operations element-wise**

**Use case-2**

   - NumPy offers significantly lower processing time compared to lists.

In [29]:
import time  

# Creating two large ranges of numbers  
l1 = range(1, 100000000)  
l2 = range(1, 100000000)  

# Recording the start time  
start = time.time()  

# Iterating over both lists using zip (element-wise operation)  
for i, j in zip(l1, l2):  
    pass  # No operation is performed, just iterating  

# Recording the end time  
end = time.time()  

# Printing the total time taken for iteration  
print("Time taken:", end-start)  


Time taken: 12.369544982910156


In [30]:
l=range(1,10)
for i in l:
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

In [35]:
import time

# Define two large ranges of numbers
l1 = range(1, 100000000)
l2 = range(1, 100000000)

# Record the start time
start = time.time()

# Perform element-wise multiplication of l1 and l2 using list comprehension
result = [i * j for i, j in zip(l1, l2)]

# Record the end time
end = time.time()

# Calculate and print the time taken for the operation
time_taken = end - start
print(f"Time taken: {time_taken} seconds")


Time taken: 16.67451524734497 seconds


**arange**
  - arange is same like range

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
import time
arr1=np.arange(1,100000000)
arr2=np.arange(1,100000000)
start=time.time()
arr1*arr2
end=time.time()
print("time taken:",end-start)

time taken: 0.7163853645324707


**Shape dimension**
  - **Shape:** A tuple representing the number of elements in each axis (e.g., (3, 4) means 3 rows and 4 columns).
  - **Dimension (ndim):** The number of axes in the array (e.g., a 2D array has ndim = 2).

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print(arr.shape)  # Output: (2, 3)  
print(arr.ndim)   # Output: 2  


(2, 3)
2


In [45]:
arr1.shape

(99999999,)

- **A 1D array (one-dimensional array)** in NumPy is a simple array with a single axis.

In [48]:
arr1.ndim

1

In [50]:
arr1.size

99999999

- A **2D array (two-dimensional array)** in NumPy is an array with two axes (rows and columns).

In [53]:
l1=[1,2,3,4]
l2=['A','B','C','D']

arr1=np.array([l1,l2])
print("shape:",arr1.shape)
print("dim:",arr1.ndim)
print("number of elements:",arr1.size)

shape: (2, 4)
dim: 2
number of elements: 8


In [55]:
arr1=np.array([[1,2,3,4],
               ['A','B','C','D']
              ])
print("shape:",arr1.shape)
print("dim:",arr1.ndim)
print("number of elements:",arr1.size)

shape: (2, 4)
dim: 2
number of elements: 8


In [57]:
L1=[(1,'A'),
    (2,'B'),
    (3,'C'),
    (4,'D')]

np.array(L1).shape

(4, 2)

In [59]:
arr1.shape

(2, 4)

In [61]:
np.array([
          [1,2,3,4],
          ['A','B','C','D'],
          [5,6,7,8],
          ['E','F','G','H']
])

array([['1', '2', '3', '4'],
       ['A', 'B', 'C', 'D'],
       ['5', '6', '7', '8'],
       ['E', 'F', 'G', 'H']], dtype='<U11')

**Difference Between Shape and Dim in NumPy**

- **Shape** refers to the structure of an array, specifically the number of rows and columns.

- A **1D array** has only one axis (i.e., a single row), hence it is considered one-dimensional.

- A **2D array** consists of both rows and columns, making it two-dimensional.

- While the number of rows and columns may vary, the shape focuses on the arrangement of the array in terms of rows and columns.

- The **dimension (dim)** of an array is always represented as the length of its shape.

- The **shape** is represented as a tuple (e.g., (m, n)), where:

    - m is the number of rows,
    - n is the number of columns.
- **Size** refers to the total number of elements in the array.

A **3D array (three-dimensional array)** in NumPy is an array with three axes: rows, columns, and depth (or layers). This is commonly used to represent data in multiple dimensions, such as images (height, width, color channels) or volumetric data.

In [66]:
np.array([[1,2,3],['A','B','C']])

array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U11')

In [68]:
l=[
 [[1,2,3],
 ['A','B','C']],

[[1,2,3],
 ['A','B','C']],

[[1,2,3],
 ['A','B','C']]

]

In [70]:
np.array(l)

array([[['1', '2', '3'],
        ['A', 'B', 'C']],

       [['1', '2', '3'],
        ['A', 'B', 'C']],

       [['1', '2', '3'],
        ['A', 'B', 'C']]], dtype='<U11')

In [ ]:
l1=[
 [[1,2,3],
 ['A','B','C']],

[[1,2,3],
 ['A','B','C']],

[[1,2,3],
 ['A','B','C']]

]

l2=[
 [[1,2,3],
 ['A','B','C']],

[[1,2,3],
 ['A','B','C']],

[[1,2,3],
 ['A','B','C']]

]

l=[l1,l2]
np.array(l)
2,3,rows,column

**Generate a random floating-point number between 0 and 1**

In [81]:
import random
random.random()

0.7734591057953635

In [85]:
import numpy as np
np.random.rand()

0.1069504878443237

In [87]:
np.random.rand(4,2)
# 2 rows and 2 columns

array([[0.64623883, 0.718343  ],
       [0.30653567, 0.17606333],
       [0.99281337, 0.69841789],
       [0.02579499, 0.03291961]])

In [89]:
np.random.randn(10)

array([-0.20677643,  1.68824346, -0.01393199,  0.29051906,  2.59644561,
       -0.10544782,  0.91987241, -0.46230904, -0.88258338, -1.547991  ])

**randn:**

The randn function generates data that follows a **standard normal distribution,** with a mean of 0 and a standard deviation of 1. It is commonly used to create random samples drawn from a normal distribution for various applications in data analysis and simulations.

**random**

In [93]:
np.random.random((3,3))

array([[0.32995693, 0.73174694, 0.82518059],
       [0.89608084, 0.76120094, 0.39536183],
       [0.14830151, 0.42600122, 0.78614154]])

In [95]:
np.random.rand(3,3)

array([[0.09577917, 0.95383686, 0.18449741],
       [0.46123238, 0.37270643, 0.97442394],
       [0.51705527, 0.84838211, 0.94416844]])

- **random** expects the shape to be provided in a tuple format.

- However, rand does not require the shape to be specified in tuple format.

- Many functions and code structures expect the shape argument to be provided in a tuple format.

- Therefore, using **random.random()** is considered a best practice for consistency and flexibility in handling shape arguments.

- The **random** package in Python provides basic random number generation functionality.

- **NumPy** includes its own random module, which offers:

- The ability to generate random numbers between 0 and 1.
- The shape must be provided in tuple format.
- **NumPy** also includes rand, which:

   - Generates random numbers between 0 and 1.
   - Does not require the shape to be specified in tuple format.
- **NumPy's** randn:

   - Generates random data that follows a normal distribution with a mean of 0 and a standard deviation of 1.

**Generate random integers within a specified range**

In [100]:
import random
random.randint(1,20)
# 1 and 10 both are include 

18

In [102]:
import numpy as np
random.randint(1,10)
# low (inclusive) to high (exclusive).
# 1 is include 10 is exclude

3

In [104]:
np.random.randint(1,20,size=5)

array([11, 19,  2, 12, 14])

In [106]:
np.random.randint(1,20,size=(3,2))

array([[ 6, 12],
       [13,  6],
       [18, 11]])

**Select a random number from a given list**

In [109]:
list1=[10,20,30,40,50,60,70,80]
import random
random.choice(list1)

50

In [111]:
list1=[10,20,30,40,50,60,70,80]
import numpy as np
np.random.choice(list1)

20

In [113]:
list1=range(1,200) # [i for in range(1,200)]
np.random.choice(list1,10)

array([112,  77,  31,  78, 105, 191, 187, 143,  98, 180])

In [115]:
# Avoid the repeatition
list1=range(1,200) # [i for in range(1,200)]
np.random.choice(list1,10,replace=False)

array([125, 170, 115, 102, 166,  32, 142,  11, 143,  42])

- **Statistical operations using numPy**
- **Min:** The minimum value in a dataset or array. It represents the smallest number or the lowest value.

- **Max:** The maximum value in a dataset or array. It represents the largest number or the highest value.

- **Count:** The total number of elements or observations in a dataset or array.

- **Mean:** The arithmetic average of a dataset, calculated by summing all values and dividing by the number of elements.

- **Mode:** The value that appears most frequently in a dataset.

- **Median:** The middle value in a sorted dataset, where half of the values are below and half are above it. It is less affected by outliers compared to the mean.

- **Variance:** A measure of how spread out the values in a dataset are from the mean. It is the average of the squared differences from the mean.

- **Standard Deviation:** The square root of the variance. It measures the average amount of variability or dispersion in a dataset.

- **Covariance:** A measure of the relationship between two variables, indicating how changes in one variable correspond to changes in another.

- **Correlation:** A statistical measure that describes the strength and direction of the relationship between two variables. It ranges from -1 to 1.

- **Percentile:** The value below which a given percentage of observations in a dataset fall. For example, the 50th percentile is the median.

- **Quantile:** A value that divides a dataset into equal intervals, with a specified proportion of data falling below the quantile. Quantiles include quartiles, deciles, etc.

In [118]:
import numpy as np

In [120]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

**min**

In [123]:
list1=[10,20,30,40,50,60]

In [125]:
np.min(list1)

10

In [127]:
arr1=np.array([[10,20,30],
              [1,2,3]])
arr1

array([[10, 20, 30],
       [ 1,  2,  3]])

In [129]:
arr1.shape

(2, 3)

In [131]:
np.min(arr1)

1

In [133]:
np.min(arr1,axis=0)

array([1, 2, 3])

In [135]:
np.min(arr1,axis=1)

array([10,  1])

- **Axis 0** represents the rows, meaning operations along this axis are performed column-wise.

- **Axis 1** represents the columns, meaning operations along this axis are performed row-wise.

**Sum**

In [139]:
arr1=np.array([[60,170,180],
              [10,20,30]])
arr1

array([[ 60, 170, 180],
       [ 10,  20,  30]])

In [141]:
np.sum(arr1)

470

In [143]:
np.sum(arr1,axis=0)

array([ 70, 190, 210])

In [145]:
[ 85, 89,  300]+[ 400,  455,  490]

[85, 89, 300, 400, 455, 490]

In [147]:
np.sum(arr1,axis=1)

array([410,  60])

- **Sum at the axis level** refers to computing the sum along a specific axis in a multi-dimensional array.

- axis=1 (row-wise sum):

   - Computes the sum across each row individually.
   - Each row's elements are summed separately.
- axis=0 (column-wise sum):

   - Computes the sum across each column.
   - Each column's elements are summed separately.

**mean-median**

In [151]:
list1=[78,65,78,45,57,89,122]
np.mean(list1)

76.28571428571429

In [153]:
np.sum(list1)/len(list1)

76.28571428571429

In [155]:
from functools import reduce
reduce(lambda summ,i: summ+i,list1)

534

In [157]:
summ=0
for i in list1:
    summ=summ+i
summ

534

In [159]:
list1=[1,22,23,45,57,89,121]
summ=0
[summ:=summ+i for i in list1][-1]

358

In [161]:
x=[55,35,80,78,47]
y=[45,12,25,78,12]
np.cov(x,y)

array([[384.5 , 348.75],
       [348.75, 776.3 ]])

In [163]:
import numpy as np  

# Step 1: Calculate the mean of x  
x = [15, 54, 45, 40, 50]  
x_bar = np.mean(x)  

# Step 2: Calculate the mean of y  
y = [15, 32, 34, 47, 55]  
y_bar = np.mean(y)  

# Step 3: Compute (xi - x̄) for each element in x  
x_minus_xbar = [i - x_bar for i in x]  

# Step 4: Compute (yi - ȳ) for each element in y  
y_minus_ybar = [i - y_bar for i in y]  

# Step 5: Compute the element-wise product of Step 3 and Step 4  
product_list = [i * j for i, j in zip(x_minus_xbar, y_minus_ybar)]  

# Step 6: Compute the sum of the product list  
sum_product = sum(product_list)  

# Step 7: Divide by (n - 1) to compute the final result  
result = sum_product / (len(x) - 1)  

print(result)  # Output: Covariance value  


161.64999999999998


**Variance**

In [165]:
x=[15,25,35,45,55]
import numpy as np
np.var(x)

200.0

<img class="XqHOTb IGEbUc" alt="S^2 = \frac{\sum (x_i - \bar{x})^2}{n - 1}" src="https://www.gstatic.com/education/formulas2/553212783/en/sample_variance.svg" role="img" data-csiid="d7JuZ42HLLed4-EP69DY2AM_16" data-atf="0">m

In [169]:
# Step 1: Compute the mean  
# Formula: mean = sum of all elements / total number of elements  

x = [15, 25, 35, 45, 55]  
x_mean = sum(x) / len(x)  
print("Mean of x:", x_mean)  

# Step 2: Compute (xi - x̄) for each element in x  
deviation_list = [i - x_mean for i in x]  

# Step 3: Compute the squared deviations (xi - x̄)²  
squared_deviation_list = [i ** 2 for i in deviation_list]  

# Step 4: Compute variance (sum of squared deviations / N)  
variance = sum(squared_deviation_list) / len(squared_deviation_list)  

print("Variance:", variance)  


Mean of x: 35.0
Variance: 200.0


**Sd**

In [172]:
x=[15,25,35,45,55]
np.std(x)

14.142135623730951

<img class="XqHOTb IGEbUc" alt="\sigma={\sqrt {\frac {\sum(x_{i}-{\mu})^{2}}{N}}}" src="https://www.gstatic.com/education/formulas2/553212783/en/population_standard_deviation.svg" role="img" data-csiid="k7VuZ9CdNNqZ4-EP7c-O-AI_10" data-atf="0">

In [175]:
# Step 1: Compute the mean  
x = [15, 25, 35, 45, 55]  
x_mean = sum(x) / len(x)  
print("Mean of x:", x_mean)  

# Step 2: Compute (xi - x̄) for each element in x  
deviations = [i - x_mean for i in x]  

# Step 3: Compute the squared deviations (xi - x̄)²  
squared_deviations = [i ** 2 for i in deviations]  

# Step 4: Compute standard deviation  
variance = sum(squared_deviations) / len(squared_deviations)  
std_dev = variance ** 0.5  

print("Standard Deviation:", std_dev)  


Mean of x: 35.0
Standard Deviation: 14.142135623730951


In [177]:
np.sum(np.square(x-np.mean(x)))/len(x)

200.0

**correlation**

In [180]:
x=[15,25,35,45,55]
y=[14,22,32,42,52] 
np.corrcoef(x,y)

array([[1.        , 0.99913307],
       [0.99913307, 1.        ]])

<img src="https://www.simplilearn.com/ice9/free_resources_article_thumb/Correlation_2.png" jsaction="" class="sFlh5c FyHeAf iPVvYb" style="max-width: 359px; height: 85px; margin: 27px 0px; width: 178px;" alt="What Is Correlation? A Guide for Beginners | Simplilearn" jsname="kn3ccd" aria-hidden="false">

In [183]:
import numpy as np  

# Given data  
x = [15, 25, 35, 45, 55]  
y = [14, 22, 32, 42, 52]  

# Step 1: Compute the mean of x and y  
x_bar = np.mean(x)  
y_bar = np.mean(y)  

# Step 2: Compute (xi - x̄) and (yi - ȳ)  
x_deviation = [i - x_bar for i in x]  
y_deviation = [i - y_bar for i in y]  

# Step 3: Compute the product of deviations  
deviation_product = [i * j for i, j in zip(x_deviation, y_deviation)]  

# Step 4: Compute covariance  
cov_xy = sum(deviation_product) / len(x)  

# Function to calculate standard deviation  
def standard_deviation(values):  
    mean_val = np.mean(values)  
    squared_deviations = [(i - mean_val) ** 2 for i in values]  
    variance = sum(squared_deviations) / len(values)  
    return variance ** 0.5  

# Step 5: Compute standard deviation of x and y  
sd_x = standard_deviation(x)  
sd_y = standard_deviation(y)  

print("Standard Deviation of x:", sd_x)  
print("Standard Deviation of y:", sd_y)  

# Step 6: Compute correlation coefficient  
correlation = cov_xy / (sd_x * sd_y)  
print("Correlation Coefficient:", correlation)  


Standard Deviation of x: 14.142135623730951
Standard Deviation of y: 13.588230201170424
Correlation Coefficient: 0.9991330730923518


**Euclidean Distance**
 - The Euclidean distance is the straight-line distance between two points in a multidimensional space.

<img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/300px-Euclidean_distance_2d.svg.png" decoding="async" width="300" height="207" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/450px-Euclidean_distance_2d.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/600px-Euclidean_distance_2d.svg.png 2x" data-file-width="360" data-file-height="248">

In [187]:
# Define the coordinates of two points
p = (3, 5)   # (x1, y1)  
q = (8, 10)  # (x2, y2)  

# Extract x and y coordinates  
x1, y1 = p  
x2, y2 = q  

# Compute the differences  
dx = x2 - x1  
dy = y2 - y1  

# Compute Euclidean distance  
euclidean_distance = (dx ** 2 + dy ** 2) ** 0.5  

print("Euclidean Distance:", euclidean_distance)  


Euclidean Distance: 7.0710678118654755


In [189]:
# method-2:
# Define points  
p = (3, 5)   # (x1, y1)  
q = (8, 10)  # (x2, y2)  

# Convert points to NumPy arrays  
a1 = np.array(p)  
a2 = np.array(q)  

# Compute Euclidean distance using NumPy  
euclidean_distance = np.sqrt(np.sum(np.square(a2 - a1)))  

print("Euclidean Distance:", euclidean_distance)  


Euclidean Distance: 7.0710678118654755


In [191]:
np.array([15,25,35])-np.array([1,2,3])

array([14, 23, 32])

**Linear Algebra**
   - Package Name: numpy
   - Class Name: linalg
   - Method Name: norm


- The norm function in the linalg class of NumPy is used to compute the norm of a vector or matrix. It calculates the magnitude or length of a vector, or the Frobenius norm for matrices.

In [194]:
# Method- 3
# Import necessary functions from numpy
from numpy.linalg import norm
from numpy import var, std, mean
import numpy as np

# Define points p and q
p = (3, 5)   # (x1, y1)
q = (8, 10)  # (x2, y2)

# Convert points into NumPy arrays
a1 = np.array(p)
a2 = np.array(q)

# Compute the Euclidean distance (norm of the difference)
euclidean_distance = np.linalg.norm(a1 - a2)

# Print the result
print("Euclidean Distance:", euclidean_distance)


Euclidean Distance: 7.0710678118654755


**Find the roots**

In [201]:
# Define the coefficients of the quadratic equation x^2 - 3x + 2
coeff = [1, -3, 2]

# Compute the roots of the quadratic equation
roots = np.roots(coeff)

# Print the roots
print("Roots of the equation:", roots)


Roots of the equation: [2. 1.]
